### ISSUE TITLE
Add the ability for nesting all key/value pairs

### ISSUE THREAD

**Issue by gremo** [igorw/ConfigServiceProvider#7]
Sorry for bother you two times in a day :)

Since all configuration values are merged in the main `$app` "namespace" i would add the ability for nesting all key/value pairs under a root node. This would avoid collisions:

```
# config.yml

security:
  authentication_header_regex: ^FID (\S+):(\S+)$
  cache_dir: %app_dir%/cache/security_cache
  firewalls:
    secured:
      pattern: ^/
      hmac: { algo: sha256 }
```

```
$app->register(new ConfigServiceProvider(__DIR__ . '/../app/config.yml'));
$app->register(new SecurityServiceProvider(), array(
    'security.firewalls' => $app['security']['firewalls']
));
```

Registering the security provider (hold by `$app['security']`) is going to override my security settings. Passing a `$root` option could solve the problem:

```
$app->register(new ConfigServiceProvider(__DIR__ . "/../app/config.yml", $replacement, 'options'));
```

So that all settings go under `$app['options']`.

**Comment by igorw** [comment]
The way it is intended to be used is:

```
# config.yml
security.authentication_header_regex: ^FID (\S+):(\S+)$
security.cache_dir: %app_dir%/cache/security_cache
security.firewalls:
    secured:
        pattern: ^/
        hmac: { algo: sha256 }
```

What I'm not opposed to is having a "key prefix" that is added to all top-level keys.

So you could do:

```
# security.yml
authentication_header_regex: ^FID (\S+):(\S+)$
cache_dir: %app_dir%/cache/security_cache
firewalls:
    secured:
        pattern: ^/
        hmac: { algo: sha256 }
```

And then:

```
$app->register(new ConfigServiceProvider(__DIR__ . "/../app/security.yml", $replacement, 'security'));
```

How does that sound?

**Comment by gremo** [comment]
Your first code sample seems a bit redundant, isn't it? :). Your solution (prefixing all keys) may work. The latter seems a bit overkill for a small project (splitting configuration between many files). But i think that keeping all config params under the same "section" (like Sf2 does) make it more readable. In this case, a simple "prefix" won't do the trick. You should make all config keys go under the root prefix, like:

```
# Doctrine DBAL params
db:
  host: localhost
  username: aname
  password: apass

# Security params
security:
  authentication_header_regex: ^FID (\S+):(\S+)$
  cache_dir: %app_dir%/cache/security_cache
  firewalls:
    secured:
      pattern: ^/
      hmac: { algo: sha256 }

# Translator params
translation:
  fallback: fr
```

```
$app->register(new ConfigServiceProvider(__DIR__ . "/../app/config.yml", $replacement, 'config'));

$app->register(new DoctrineServiceProvider(array('db.options' => $app['config']['database']));

$app->register(new TranslationServiceProvider(), array(
    'locale_fallback' => $app['config']['translation']['fallback'],
))
```

You can also define a default prefix, so the config should be noob-proof (for people like me :D). That is:

```
# config.yml
security: I really need this string
```

Will not be overridden by the security service loader.

Anyway, it's up to you, just giving a suggestion!
